#!/usr/bin/env python3
"""Regenerates src/casefold.zig from Unicode full case folding.

CommonMark 0.31.2 §4.7 normalizes link labels with Unicode case folding, not
ASCII lowercasing. Python's `str.casefold()` is the full (C+F) fold, so this
runs offline and reproducibly.

Only non-ASCII code points whose fold differs from themselves are emitted;
ASCII is handled arithmetically by the caller.

    python3 tools/gen_casefold.py > src/casefold.zig
"""
import sys

entries = []
for cp in range(0x80, 0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    folded = ch.casefold()
    if folded != ch:
        entries.append((ch, folded))


def zig_str(s: str) -> str:
    out = []
    for b in s.encode("utf-8"):
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\x%02x" % b)
    return '"' + "".join(out) + '"'


w = sys.stdout.write
w("//! Generated by tools/gen_casefold.py — do not edit by hand.\n")
w("//! Unicode full case folding (CommonMark 0.31.2 §4.7), %d entries.\n" % len(entries))
w('const std = @import("std");\n\n')
w("/// UTF-8 encoding of a non-ASCII code point → its folded UTF-8 text.\n")
w("/// Folding can lengthen a character (`\\u{1E9E}` → `ss`), so values are byte slices.\n")
w("pub const folds = std.StaticStringMap([]const u8).initComptime(.{\n")
for ch, folded in entries:
    w("    .{ %s, %s },\n" % (zig_str(ch), zig_str(folded)))
w("});\n")
