#!/usr/bin/env python3
"""Regenerates src/entities.zig from the HTML5 named character reference table.

CommonMark 0.31.2 §6.5 requires the full set of semicolon-terminated HTML5
entities. Python's stdlib ships that table (derived from the WHATWG
entities.json), so this runs offline and reproducibly.

    python3 tools/gen_entities.py > src/entities.zig
"""
import sys
from html.entities import html5

names = sorted(k[:-1] for k in html5 if k.endswith(";"))

def zig_str(s: str) -> str:
    out = []
    for b in s.encode("utf-8"):
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\x%02x" % b)
    return '"' + "".join(out) + '"'

w = sys.stdout.write
w("//! Generated by tools/gen_entities.py — do not edit by hand.\n")
w("//! HTML5 named character references (CommonMark 0.31.2 §6.5), %d entries.\n" % len(names))
w("const std = @import(\"std\");\n\n")
w("/// Entity name without `&` or `;` → its UTF-8 replacement text.\n")
w("/// A few entities expand to two code points, so values are byte slices.\n")
w("pub const named_entities = std.StaticStringMap([]const u8).initComptime(.{\n")
for n in names:
    w("    .{ %s, %s },\n" % (zig_str(n), zig_str(html5[n + ";"])))
w("});\n")
